config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  root 'static_pages#home'

  resources :gossips do
  	resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	
	belongs_to :gossip
	validates	:anonymous_commentator, presence: true 
	validates	:body, presence: true 

end

app/models/gossip.rb
class Gossip < ApplicationRecord
	
	has_many :comments
	validates	:anonymous_author, presence: true 
	validates	:content, presence: true 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  	@comment=Comment.new
  end

  def create
  	@comment = Comment.new(comment_params)
    @comment.gossip_id = params[:gossip_id]
    @comment.save
    redirect_to gossip_path
  end 

  def edit
  	@comment = Comment.find(params[:gossip_id])
  end


  private
    def comment_params
      params.require(:comment).permit(:anonymous_commentor, :body)
    end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

	def new
		@gossip=Gossip.new
	end

	def create
		@gossip=Gossip.create(gossip_params)

	    redirect_to gossip_path(@gossip.id)
	end

	def show
		@gossip = Gossip.find_by(id: params[:id]) 
	end 

	def edit
		@gossip = Gossip.find_by(id: params[:id]) 
	end

	def update
		@gossip = Gossip.find_by(id: params[:id])
		@gossip.update(gossip_params)

		redirect_to gossip_path(@gossip.id)
	end

	def destroy
		@gossip = Gossip.find_by(id: params[:id])
		@gossip.destroy
    	
    	redirect_to gossips_path
	end

	def index
		@gossips=Gossip.all
	end

	private
	def gossip_params
		params.require(:gossip).permit(:anonymous_author, :content)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/gossips/edit.html.erb
<h1> Edit le Gossip </h1>

<%=form_for @gossip, url:{action:"update"} do |f| %>
	
	<div class="form-group">

		<label> Rentre un pseudo </label> 

		<%= f.text_field :anonymous_author, class:'form_control' %> 
		
	</div>

	<div class="form-group">

		<label> Contenu du Gossip </label> 

		<%= f.text_area :content, class:'form_control' %> 
		
	</div>


	<div class="form-group">
         <button type=submit class="btn btn-primary">Modifier le gossip</button>
            
         <a href="<%= gossip_path(@gossip.id) %>" class="btn btn-danger" data-method="DELETE">Supprimer le gossip</a>
    </div>


<% end %>

app/views/gossips/index.html.erb
<h1> Index des Gossips </h1>

<% @gossips.each do |gossip| %>
    <h2><%= gossip.anonymous_author %></h2> 
    <h5><%= gossip.content %></h5>
    <p><a href="<%= gossip_path(gossip.id) %>" class="btn btn-primary"> Voir Gossip</a></p>
<% end %>

app/views/gossips/new.html.erb
<br></br>
<h1> Balance ton GOSSIP </h1><br></br>

	<%=form_for @gossip, url:{action:"create"} do |f| %>
		
		<div class="form-group">

			<label> Rentre un pseudo </label> 

			<%= f.text_field :anonymous_author, class:'form_control' %> 
		
		</div>

		<div class="form-group">

			<label> Contenu du Gossip </label> 

			<%= f.text_area :content, class:'form_control' %> 
		
		</div>


		<div class="form-group">

			<button type="submit" class="btn btn-primary"> Enregistrer le Gossip </button>
		
		</div> 

	<% end %>

<a href="<%= gossips_path %>" class="btn btn-primary"> Revenir aux Gossips >

app/views/gossips/show.html.erb
<h1> ET CA BLABLATE </h1><br>

<h1><%= @gossip.anonymous_author %></h1><br>
<h2>Numéro de Gossip :<%= @gossip.id %></h2><br>
<h2><%= @gossip.content %></h2>

<div>
	<a href=" <%= edit_gossip_path %>" class="btn btn-primary"> Edit le Gossip</a>
 	<a href=" <%= gossips_path %>" class="btn btn-primary"> Revenir aux Gossips</a>
 	<br></br>
	<br></br>
	<h3>Comment on This Post</h3>
	
	<%=form_for [@gossip, Comment.new] do |f| %>
	
		<div class="form-group">

			<label> Rentre un pseudo </label> 

			<%= f.text_field :anonymous_commentor, class:'form_control' %> 
		
		</div>

		<div class="form-group">

			<label> Fouts ton comm' et fais la/le Sal/e!! </label> 

			<%= f.text_area :body, class:'form_control' %> 
		
			<button type=submit class="btn btn-primary">Comment!!</button>
		
		</div>
	
	<% end %>
 
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", root_path %></li>
        <li><%= link_to "Index des gossips", gossips_path %></li>
        <li><%= link_to "Nouveau gossip", new_gossip_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1> The Gossip </h1>



<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les Gossips 🎓
  </h3>
  
  <a href=" <%= new_gossip_path%>" class="btn btn-primary"> Gossip</a>
  
</div>

<body {
    margin-top: 50px !important;
}>